### ISSUE TITLE
Error in test cases

### ISSUE THREAD

**Issue by jveer634** [MystenLabs/blackjack-sui#37]
Facing an error in the test cases while using scenario module. The compiler is giving an error while borrowing the `scenario_val` as a mutable reference since the `scenario_val` is an immutable varible

![image](https://github.com/MystenLabs/blackjack-sui/assets/47923507/e1015a72-afd5-4f12-a89c-384f1d49cb04)

https://github.com/MystenLabs/blackjack-sui/blob/941dbd0c0e4c925ee9d171fbc162004a989ef2f1/move/blackjack/tests/counter_tests.move#L29

Here is my `Move.toml` file

```toml
[package]
name = "sui_contracts"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }


[addresses]
sui_contracts = "0x0"


[dev-dependencies]
# The dev-dependencies section allows overriding dependencies for `--test` and
# `--dev` modes. You can introduce test-only dependencies here.
# Local = { local = "../path/to/dev-build" }

[dev-addresses]
# The dev-addresses section allows overwriting named addresses for the `--test`
# and `--dev` modes.
# alice = "0xB0B"
```
